{
  "hash": "3c8448cad53a79025284f1ee566d53ec",
  "result": {
    "engine": "knitr",
    "markdown": "## 第7章\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, readxl, sjPlot, marginaleffects, car, modelsummary)\n# コード7-1\n# library(tidyverse)\nfirmdata <- readxl::read_xlsx(\"data/MktRes_firmdata.xlsx\")\nfirmdata19 <- firmdata %>%\n  filter(fyear == 2019)\n#産業名を特定したオブジェクト\"Retail\"の作成\nretail <- c(\"Retail Stores, NEC\", \"Supermarket Chains\",\n            \"Department Stores\")\n# Retail を使ったカテゴリー変数の作成\nfirmdata19 <- firmdata19 %>%\n  mutate(format = ifelse(ind_en %in% retail, \"Retail\", \"Other\"))\n#カテゴリーの頻度チェック\nwith(firmdata19, table(format))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nformat\n Other Retail \n    90     56 \n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-2\nfit.d1 <- lm(op ~ mkexp + format, data = firmdata19)\nsummary(fit.d1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = op ~ mkexp + format, data = firmdata19)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.095926 -0.031427 -0.008661  0.014345  0.261068 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   0.101694   0.008833  11.514  < 2e-16 ***\nmkexp        -0.066003   0.024959  -2.644 0.009097 ** \nformatRetail -0.031770   0.009303  -3.415 0.000831 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.05368 on 143 degrees of freedom\nMultiple R-squared:  0.1379,\tAdjusted R-squared:  0.1258 \nF-statistic: 11.44 on 2 and 143 DF,  p-value: 2.469e-05\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-3\nfirmdata19 <- firmdata19 %>%\n  mutate(retail = ifelse(format == \"Retail\", 1, 0))\n\n# 確認\nwith(firmdata19, table(retail, format))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      format\nretail Other Retail\n     0    90      0\n     1     0     56\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-4\nfit.d2 <- lm(op ~ mkexp + retail, data = firmdata19)\nsummary(fit.d2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = op ~ mkexp + retail, data = firmdata19)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.095926 -0.031427 -0.008661  0.014345  0.261068 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.101694   0.008833  11.514  < 2e-16 ***\nmkexp       -0.066003   0.024959  -2.644 0.009097 ** \nretail      -0.031770   0.009303  -3.415 0.000831 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.05368 on 143 degrees of freedom\nMultiple R-squared:  0.1379,\tAdjusted R-squared:  0.1258 \nF-statistic: 11.44 on 2 and 143 DF,  p-value: 2.469e-05\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-5\nfit.d3 <- lm(op ~ mkexp * retail, data = firmdata19)\nsummary(fit.d3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = op ~ mkexp * retail, data = firmdata19)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.100914 -0.027907 -0.006023  0.020847  0.254339 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   0.112780   0.009123  12.362  < 2e-16 ***\nmkexp        -0.106801   0.026898  -3.971 0.000113 ***\nretail       -0.099242   0.021752  -4.563 1.08e-05 ***\nmkexp:retail  0.205666   0.060393   3.405 0.000859 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0518 on 142 degrees of freedom\nMultiple R-squared:  0.203,\tAdjusted R-squared:  0.1862 \nF-statistic: 12.06 on 3 and 142 DF,  p-value: 4.461e-07\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-6\n# install.packages(\"sjPlot\")\n\n# コード7-7\n# # library(sjPlot)\npred <- plot_model(fit.d3,\n  type = \"pred\",\n  terms = c(\"mkexp\", \"retail\"),\n  ci.lvl = .95) +\n  labs(\n    title = \"Slope Analysis\",\n    subtitle = \"(Predicted Values of Profitability with 95% Confidence Intervals)\",\n    x = \"Marketing Expense\",\n    y = \"Profitability\"\n  ) + scale_color_discrete(name = \"Retail Dummy\")\npred\n```\n\n::: {.cell-output-display}\n![](chapter07_files/figure-pdf/unnamed-chunk-1-1.png){fig-align='center' fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# コード7-8\nHeadphone07 <- readr::read_csv(\"data/headphone07.csv\", na = \".\")\n\n#データフレームの確認\nglimpse(Headphone07)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 221\nColumns: 4\n$ ID        <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1~\n$ sales     <dbl> 118.8377, 548.6312, 197.3075, 104.2657, 748.8251, 947.8850, ~\n$ rd        <dbl> 404.0893, 252.1270, 444.3374, 407.5876, 841.7605, 336.8744, ~\n$ promotion <dbl> 75.63163, 102.74572, 97.98040, 83.46613, 105.69250, 80.17476~\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-9\nfit_int <- lm(sales ~ rd * promotion, data = Headphone07)\nsummary(fit_int)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ rd * promotion, data = Headphone07)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-46.522 -12.861  -0.638  13.578  70.667 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   2.033e+04  1.090e+02   186.5   <2e-16 ***\nrd           -5.187e+01  2.844e-01  -182.4   <2e-16 ***\npromotion    -1.914e+02  1.052e+00  -181.9   <2e-16 ***\nrd:promotion  4.979e-01  2.730e-03   182.4   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.55 on 217 degrees of freedom\nMultiple R-squared:  0.9935,\tAdjusted R-squared:  0.9934 \nF-statistic: 1.111e+04 on 3 and 217 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-10\nHeadphone07 <- Headphone07 %>%\n  mutate(promotion_c = promotion - mean(promotion, na.rm = TRUE),\n         rd_c = rd - mean(rd, na.rm = TRUE))\n\nfit_int_c <- lm(sales ~ rd_c * promotion_c , data = Headphone07)\nsummary(fit_int_c)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ rd_c * promotion_c, data = Headphone07)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-46.522 -12.861  -0.638  13.578  70.667 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      382.27812    1.51459  252.40   <2e-16 ***\nrd_c              -0.91767    0.01196  -76.75   <2e-16 ***\npromotion_c        0.69039    0.03972   17.38   <2e-16 ***\nrd_c:promotion_c   0.49792    0.00273  182.37   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 20.55 on 217 degrees of freedom\nMultiple R-squared:  0.9935,\tAdjusted R-squared:  0.9934 \nF-statistic: 1.111e+04 on 3 and 217 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-11\nleg = c(\"Mean - 1sd\", \"Mean\", \"Mean + 1sd\")\nint_fig1 <- plot_model(fit_int_c,\n type = \"int\",\n mdrt.values = \"meansd\",\n ci.lvl = .9999999999) +\n  labs(\n    title = \"Predicted values of Sales(R&D * Promotion)\",\n    x = \"R&D Investment\",\n    y = \"Sales\") +\n  scale_color_discrete(\n    name = \"Promotion level\",\n    labels = leg)\nint_fig1\n```\n\n::: {.cell-output-display}\n![](chapter07_files/figure-pdf/unnamed-chunk-1-2.png){fig-align='center' fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# コード7-12\n# install.packages(\"marginaleffects\")\n\n# コード7-13\n# library(marginaleffects)\nint_fig2 <- plot_slopes(fit_int_c, variables = \"rd_c\",\n  condition = \"promotion_c\", conf_level = .99999999) +\n  labs(title = \"Marginal effects of R&D on Sales\",\n       x = \"Promotion\", y = \"Slope of R&D on Sales\") +\n  geom_hline(aes(yintercept = 0), linetype = \"dashed\")\nint_fig2\n```\n\n::: {.cell-output-display}\n![](chapter07_files/figure-pdf/unnamed-chunk-1-3.png){fig-align='center' fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# コード7-14\nfirmdata19 <- firmdata19 %>%\n  mutate(mkexp_c = mkexp - mean(mkexp),\n         asset_c = total_assets - mean(total_assets))\nfit_int2 <- lm(op ~ mkexp_c * asset_c, data = firmdata19)\nint_fig3 <- plot_slopes(fit_int2, variables = \"mkexp_c\",\n  condition = \"asset_c\", conf_level = 0.99) +\n  geom_hline(aes(yintercept = 0), linetype = \"dashed\")\nint_fig3\n```\n\n::: {.cell-output-display}\n![](chapter07_files/figure-pdf/unnamed-chunk-1-4.png){fig-align='center' fig-pos='H'}\n:::\n\n```{.r .cell-code}\n# コード7-15\nfirmdata19 <- firmdata19 %>%\n  mutate(adv = (adv - mean(adv)) / sd(adv),\n         rd = (rd - mean(rd)) / sd(rd),\n         ad_rd = adv + rd)\nfit_linear <- lm(sales ~ adv + rd, data = firmdata19)\nsummary(fit_linear) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ adv + rd, data = firmdata19)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-4357995  -463348  -236824   123663  2692251 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1199403      74285  16.146   <2e-16 ***\nadv          1632326      74996  21.766   <2e-16 ***\nrd             29915      74996   0.399    0.691    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 897600 on 143 degrees of freedom\nMultiple R-squared:  0.7711,\tAdjusted R-squared:  0.7679 \nF-statistic: 240.8 on 2 and 143 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-16\nfit_comp <- lm(sales ~ adv + ad_rd, data = firmdata19)\nsummary(fit_comp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sales ~ adv + ad_rd, data = firmdata19)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-4357995  -463348  -236824   123663  2692251 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  1199403      74285  16.146   <2e-16 ***\nadv          1602411     111739  14.341   <2e-16 ***\nad_rd          29915      74996   0.399    0.691    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 897600 on 143 degrees of freedom\nMultiple R-squared:  0.7711,\tAdjusted R-squared:  0.7679 \nF-statistic: 240.8 on 2 and 143 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-17\nfit_prod <- lm(log(sales) ~ log(labor_cost) + log(ppent),\n  data = firmdata19)\n\nsummary(fit_prod) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(sales) ~ log(labor_cost) + log(ppent), data = firmdata19)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.40821 -0.36129 -0.00933  0.38591  1.66673 \n\nCoefficients:\n                Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      3.17129    0.31733   9.994   <2e-16 ***\nlog(labor_cost)  0.53739    0.03679  14.605   <2e-16 ***\nlog(ppent)       0.34588    0.02797  12.366   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.5169 on 143 degrees of freedom\nMultiple R-squared:  0.8747,\tAdjusted R-squared:  0.8729 \nF-statistic: 499.1 on 2 and 143 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-18\nprice <- readr::read_csv(\"data/price_data.csv\")\n\nfit_q <- lm(log(q) ~ log(p), data = price)\nsummary(fit_q) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(q) ~ log(p), data = price)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-1.11220 -0.13668  0.02804  0.16166  0.51039 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  9.47781    0.08135   116.5   <2e-16 ***\nlog(p)      -0.18008    0.01354   -13.3   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.2309 on 998 degrees of freedom\nMultiple R-squared:  0.1506,\tAdjusted R-squared:  0.1497 \nF-statistic: 176.9 on 1 and 998 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-19\n# install.packages(\"car\")\n\n# コード7-20\n# library(car)\nlinearHypothesis(fit_q, c(\"log(p)= -1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nlog(p) = - 1\n\nModel 1: restricted model\nModel 2: log(q) ~ log(p)\n\n  Res.Df     RSS Df Sum of Sq      F    Pr(>F)    \n1    999 248.811                                  \n2    998  53.225  1    195.59 3667.3 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード7-21\n# install.packages(\"modelsummary\")\n\n# コード7-22\n# library(modelsummary)\nmsummary(fit_int, statistic = 'conf.int')\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]},\ncolumn{2}={}{halign=c,},\ncolumn{1}={}{halign=l,},\nhline{10}={1,2}{solid, black, 0.05em},\n}                     %% tabularray inner close\n\\toprule\n& (1) \\\\ \\midrule %% TinyTableHeader\n(Intercept) & \\num{20326.588} \\\\\n& [\\num{20111.797}, \\num{20541.378}] \\\\\nrd & \\num{-51.872} \\\\\n& [\\num{-52.433}, \\num{-51.312}] \\\\\npromotion & \\num{-191.431} \\\\\n& [\\num{-193.505}, \\num{-189.358}] \\\\\nrd × promotion & \\num{0.498} \\\\\n& [\\num{0.493}, \\num{0.503}] \\\\\nNum.Obs. & \\num{221} \\\\\nR2 & \\num{0.994} \\\\\nR2 Adj. & \\num{0.993} \\\\\nAIC & \\num{1969.2} \\\\\nBIC & \\num{1986.2} \\\\\nLog.Lik. & \\num{-979.617} \\\\\nF & \\num{11110.648} \\\\\nRMSE & \\num{20.36} \\\\\n\\bottomrule\n\\end{tblr}\n\\end{table}\n:::\n\n```{.r .cell-code}\n# コード7-23\nmsummary(fit_int, gof_omit = \"Log.Lik.|AIC|BIC|RMSE\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]},\ncolumn{2}={}{halign=c,},\ncolumn{1}={}{halign=l,},\nhline{10}={1,2}{solid, black, 0.05em},\n}                     %% tabularray inner close\n\\toprule\n& (1) \\\\ \\midrule %% TinyTableHeader\n(Intercept) & \\num{20326.588} \\\\\n& (\\num{108.978}) \\\\\nrd & \\num{-51.872} \\\\\n& (\\num{0.284}) \\\\\npromotion & \\num{-191.431} \\\\\n& (\\num{1.052}) \\\\\nrd × promotion & \\num{0.498} \\\\\n& (\\num{0.003}) \\\\\nNum.Obs. & \\num{221} \\\\\nR2 & \\num{0.994} \\\\\nR2 Adj. & \\num{0.993} \\\\\nF & \\num{11110.648} \\\\\n\\bottomrule\n\\end{tblr}\n\\end{table}\n:::\n\n```{.r .cell-code}\n# コード7-24\nvar_nam <- c(\"rd\" = \"R&D\", \"promotion\" = \"Promotion\",\n             \"rd:promotion\" = \"R&D * Promotion\",\n             \"rd_c\" = \"R&D_c\", \"promotion_c\" = \"Promotion_c\",\n             \"rd_c:promotion_c\" = \"R&D_c * Promotion_c\",\n             \"(Intercept)\" = \"定数項\")\nInt <- list()\nInt[[\"Without centering\"]] <- fit_int\nInt[[\"With centering\"]] <- fit_int_c\n\nmsummary(Int,\n  coef_map = var_nam,\n  title = \"Comparing Interaction Models\",\n  notes = \"Values in [ ] show 95% confidence intervals\",\n  stars = TRUE,\n  statistic = 'conf.int', conf_level = .95,\n  gof_omit = \"Log.Lik.|AIC|BIC|RMSE\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\ncaption={Comparing Interaction Models},\nnote{}={+ p \\num{< 0.1}, * p \\num{< 0.05}, ** p \\num{< 0.01}, *** p \\num{< 0.001}},\nnote{ }={Values in [ ] show 95\\% confidence intervals},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]},\ncolumn{2,3}={}{halign=c,},\ncolumn{1}={}{halign=l,},\nhline{16}={1,2,3}{solid, black, 0.05em},\n}                     %% tabularray inner close\n\\toprule\n& Without centering & With centering \\\\ \\midrule %% TinyTableHeader\nR\\&D & \\num{-51.872}*** &  \\\\\n& [\\num{-52.433}, \\num{-51.312}] &  \\\\\nPromotion & \\num{-191.431}*** &  \\\\\n& [\\num{-193.505}, \\num{-189.358}] &  \\\\\nR\\&D * Promotion & \\num{0.498}*** &  \\\\\n& [\\num{0.493}, \\num{0.503}] &  \\\\\nR\\&D\\_c &  & \\num{-0.918}*** \\\\\n&  & [\\num{-0.941}, \\num{-0.894}] \\\\\nPromotion\\_c &  & \\num{0.690}*** \\\\\n&  & [\\num{0.612}, \\num{0.769}] \\\\\nR\\&D\\_c * Promotion\\_c &  & \\num{0.498}*** \\\\\n&  & [\\num{0.493}, \\num{0.503}] \\\\\n定数項 & \\num{20326.588}*** & \\num{382.278}*** \\\\\n& [\\num{20111.797}, \\num{20541.378}] & [\\num{379.293}, \\num{385.263}] \\\\\nNum.Obs. & \\num{221} & \\num{221} \\\\\nR2 & \\num{0.994} & \\num{0.994} \\\\\nR2 Adj. & \\num{0.993} & \\num{0.993} \\\\\nF & \\num{11110.648} & \\num{11110.648} \\\\\n\\bottomrule\n\\end{talltblr}\n\\end{table}\n:::\n\n```{.r .cell-code}\n# コード7-25\nmsummary(Int,\n  title = \"Comparing Interaction Models\",\n  notes = \"Values in [ ] show 95% confidence intervals\",\n  stars = TRUE,\n  statistic =  'conf.int', conf_level = .95,\n  gof_omit = \"Log.Lik.|AIC|BIC|RMSE\",\n  output = \"latex\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\ncaption={Comparing Interaction Models},\nnote{}={+ p \\num{< 0.1}, * p \\num{< 0.05}, ** p \\num{< 0.01}, *** p \\num{< 0.001}},\nnote{ }={Values in [ ] show 95\\% confidence intervals},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]},\ncolumn{2,3}={}{halign=c,},\ncolumn{1}={}{halign=l,},\nhline{16}={1,2,3}{solid, black, 0.05em},\n}                     %% tabularray inner close\n\\toprule\n& Without centering & With centering \\\\ \\midrule %% TinyTableHeader\n(Intercept) & \\num{20326.588}*** & \\num{382.278}*** \\\\\n& [\\num{20111.797}, \\num{20541.378}] & [\\num{379.293}, \\num{385.263}] \\\\\nrd & \\num{-51.872}*** &  \\\\\n& [\\num{-52.433}, \\num{-51.312}] &  \\\\\npromotion & \\num{-191.431}*** &  \\\\\n& [\\num{-193.505}, \\num{-189.358}] &  \\\\\nrd × promotion & \\num{0.498}*** &  \\\\\n& [\\num{0.493}, \\num{0.503}] &  \\\\\nrd\\_c &  & \\num{-0.918}*** \\\\\n&  & [\\num{-0.941}, \\num{-0.894}] \\\\\npromotion\\_c &  & \\num{0.690}*** \\\\\n&  & [\\num{0.612}, \\num{0.769}] \\\\\nrd\\_c × promotion\\_c &  & \\num{0.498}*** \\\\\n&  & [\\num{0.493}, \\num{0.503}] \\\\\nNum.Obs. & \\num{221} & \\num{221} \\\\\nR2 & \\num{0.994} & \\num{0.994} \\\\\nR2 Adj. & \\num{0.993} & \\num{0.993} \\\\\nF & \\num{11110.648} & \\num{11110.648} \\\\\n\\bottomrule\n\\end{talltblr}\n\\end{table}\n:::\n:::\n\n\n",
    "supporting": [
      "chapter07_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}