{
  "hash": "bcff275a01139620e729d58d8fe6844b",
  "result": {
    "engine": "knitr",
    "markdown": "## 第8章\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, readxl, modelsummary, mfx, DescTools, mlogit)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# コード8-1\ndf1 <- data.frame(\n    Y = c(0, 0, 0, 0, 0, 1, 1, 1, 1),\n    X = c(3.4, 5.22, 7.06, 2.81, 4.11, 10.34, 13.67, 15.99, 9.09)\n  )\nlpm1 <- lm(Y ~ X, data = df1)\npred_lpm1 <- predict(lpm1)\npred_lpm1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           1            2            3            4            5            6 \n-0.006342894  0.173357681  0.355032986 -0.064597476  0.063760077  0.678888967 \n           7            8            9 \n 1.007681776  1.236750640  0.555468243 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# コード8-2\nchoice_df <- readxl::read_xlsx(\"data/choice_data.xlsx\")\nhead(choice_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 x 6\n     y1    y2    p1    p2    a1    a2\n  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>\n1     1     0 10.7  16.8      0     1\n2     0     1 11.6   9.15     1     0\n3     1     0  8.97  9.31     1     0\n4     1     0  4.62  8.03     0     0\n5     1     0  7.81 19.2      1     1\n6     1     0  7.49  8.84     0     0\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# コード8-3\nprobit1 <- glm(y1 ~ p1 + a1,\n               family = binomial(link = probit),\n               data = choice_df)\nsummary(probit1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = y1 ~ p1 + a1, family = binomial(link = probit), \n    data = choice_df)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  2.04117    0.22350   9.133  < 2e-16 ***\np1          -0.24720    0.02213 -11.171  < 2e-16 ***\na1           0.62763    0.08656   7.251 4.13e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1384.5  on 999  degrees of freedom\nResidual deviance: 1205.5  on 997  degrees of freedom\nAIC: 1211.5\n\nNumber of Fisher Scoring iterations: 3\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# コード8-4\nols1 <- lm(y1 ~ p1 + a1,\n           data = choice_df)\nlogit1 <- glm(y1 ~ p1 + a1,\n              family = binomial(link = logit),\n              data = choice_df)\nmodels <- list()\nmodels[[\"Linear probability model\"]] <- ols1\nmodels[[\"Probit model\"]] <- probit1\nmodels[[\"Logit model\"]] <- logit1\nmodelsummary(models,\n             title = \"モデル比較\",\n             notes = \"Values in [ ] show robust standard errors\",\n             stars = TRUE,\n             statistic = \"std.error\",\n             vcov = \"robust\",\n             gof_map = \"nobs\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\ncaption={モデル比較},\nnote{}={+ p \\num{< 0.1}, * p \\num{< 0.05}, ** p \\num{< 0.01}, *** p \\num{< 0.001}},\nnote{ }={Values in [ ] show robust standard errors},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]Q[]},\ncolumn{2,3,4}={}{halign=c,},\ncolumn{1}={}{halign=l,},\nhline{8}={1,2,3,4}{solid, black, 0.05em},\n}                     %% tabularray inner close\n\\toprule\n& Linear probability model & Probit model & Logit model \\\\ \\midrule %% TinyTableHeader\n(Intercept) & \\num{1.196}*** & \\num{2.041}*** & \\num{3.332}*** \\\\\n& (\\num{0.065}) & (\\num{0.212}) & (\\num{0.361}) \\\\\np1 & \\num{-0.085}*** & \\num{-0.247}*** & \\num{-0.404}*** \\\\\n& (\\num{0.006}) & (\\num{0.021}) & (\\num{0.036}) \\\\\na1 & \\num{0.221}*** & \\num{0.628}*** & \\num{1.035}*** \\\\\n& (\\num{0.029}) & (\\num{0.087}) & (\\num{0.145}) \\\\\nNum.Obs. & \\num{1000} & \\num{1000} & \\num{1000} \\\\\n\\bottomrule\n\\end{talltblr}\n\\end{table}\n:::\n\n```{.r .cell-code}\n# 適合度指標において，サンプルサイズ (\"nobs\") のみ表示するという指示\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# コード8-5\n# Average Marginal Effects（限界効果の平均）\nprobit1_ame <- probitmfx(y1 ~ p1 + a1,\n                         data = choice_df, atmean = FALSE)\nprobit1_ame\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nprobitmfx(formula = y1 ~ p1 + a1, data = choice_df, atmean = FALSE)\n\nMarginal Effects:\n        dF/dx  Std. Err.        z     P>|z|    \np1 -0.0847786  0.0060787 -13.9469 < 2.2e-16 ***\na1  0.2188866  0.0289816   7.5526 4.266e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\ndF/dx is for discrete change for the following variables:\n\n[1] \"a1\"\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# コード8-7\n# Marginal Effects at Mean（平均値における限界効果）\nprobit1_mem <- probitmfx(y1 ~ p1 + a1,\n                         data = choice_df, atmean = TRUE)\nprobit1_mem\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nprobitmfx(formula = y1 ~ p1 + a1, data = choice_df, atmean = TRUE)\n\nMarginal Effects:\n        dF/dx  Std. Err.        z     P>|z|    \np1 -0.0984235  0.0088074 -11.1750 < 2.2e-16 ***\na1  0.2446609  0.0324366   7.5427 4.602e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\ndF/dx is for discrete change for the following variables:\n\n[1] \"a1\"\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# コード8-8\nmarginal <- c(\n  \"p1 marginal\" = \"p1\",\n  \"a1 marginal\" = \"a1\"\n)\n\nmarg_model <- list(\n  \"(1) Probit_AME\" <- probit1_ame,\n  \"(2) Probit_MEM\" <- probit1_mem\n)\n\nmarg_sum <- modelsummary(\n  marg_model,\n  statistic = \"std.error\",\n  coef_map = marginal,\n  stars = TRUE,\n  shape = term:component ~ model,\n  add_rows = data.frame(\"Marginal effect type\",\n                        \"Average Marginal Effect\",\n                        \"Marginal Effect at Mean\"),\n  title = \"限界効果サマリー\",\n  gof_map = \"nobs\"\n)\nmarg_sum\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\ncaption={限界効果サマリー},\nnote{}={+ p \\num{< 0.1}, * p \\num{< 0.05}, ** p \\num{< 0.01}, *** p \\num{< 0.001}},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]},\ncolumn{2,3}={}{halign=c,},\ncolumn{1}={}{halign=l,},\nhline{6}={1,2,3}{solid, black, 0.05em},\n}                     %% tabularray inner close\n\\toprule\n& (1) & (2) \\\\ \\midrule %% TinyTableHeader\np1 & \\num{-0.085}*** & \\num{-0.098}*** \\\\\n& (\\num{0.006}) & (\\num{0.009}) \\\\\na1 & \\num{0.219}*** & \\num{0.245}*** \\\\\n& (\\num{0.029}) & (\\num{0.032}) \\\\\nNum.Obs. & \\num{1000} & \\num{1000} \\\\\nMarginal effect type & Average Marginal Effect & Marginal Effect at Mean \\\\\n\\bottomrule\n\\end{talltblr}\n\\end{table}\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# コード8-9\nDescTools::PseudoR2(probit1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n McFadden \n0.1293345 \n```\n\n\n:::\n\n```{.r .cell-code}\n# コード8-10\n\n# 価格差変数作成\nchoice_df <- choice_df %>%\n  mutate(p_ratio = p1 - p2)\n\nprobit2 <- glm(y1 ~ p_ratio + a1 + a2,\n               family = binomial(link = probit),\n               data = choice_df)\nsummary(probit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = y1 ~ p_ratio + a1 + a2, family = binomial(link = probit), \n    data = choice_df)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -0.54634    0.07756  -7.044 1.87e-12 ***\np_ratio     -0.22180    0.01524 -14.559  < 2e-16 ***\na1           0.66314    0.09162   7.238 4.55e-13 ***\na2          -0.32291    0.09884  -3.267  0.00109 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1384.5  on 999  degrees of freedom\nResidual deviance: 1066.9  on 996  degrees of freedom\nAIC: 1074.9\n\nNumber of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード8-11\nDescTools::PseudoR2(probit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMcFadden \n0.229384 \n```\n\n\n:::\n\n```{.r .cell-code}\n# コード8-12\nprobit2_ame <- probitmfx(y1 ~ p_ratio + a1 + a2,\n                         data = choice_df, atmean = FALSE)\nprobit2_ame\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nprobitmfx(formula = y1 ~ p_ratio + a1 + a2, data = choice_df, \n    atmean = FALSE)\n\nMarginal Effects:\n             dF/dx  Std. Err.        z     P>|z|    \np_ratio -0.0669199  0.0029405 -22.7581 < 2.2e-16 ***\na1       0.2036848  0.0270475   7.5306 5.049e-14 ***\na2      -0.0969891  0.0291848  -3.3233 0.0008897 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\ndF/dx is for discrete change for the following variables:\n\n[1] \"a1\" \"a2\"\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# コード8-13\ndata(Cracker, package = \"mlogit\")\nhead(Cracker, n = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   id disp.sunshine disp.keebler disp.nabisco disp.private feat.sunshine\n1   1             0            0            0            0             0\n2   1             0            0            0            0             0\n3   1             1            0            0            0             0\n4   1             0            0            0            0             0\n5   1             0            0            0            0             0\n6   1             0            0            0            0             0\n7   1             0            0            1            0             0\n8   1             0            0            1            0             0\n9   1             0            0            1            0             0\n10  1             1            0            1            0             0\n11  1             0            0            1            0             0\n12  1             0            0            0            0             0\n13  1             1            0            0            0             0\n14  1             0            1            1            0             0\n15  1             0            0            0            0             0\n16  1             0            0            1            0             0\n17  2             0            0            0            0             0\n18  2             1            0            1            0             1\n19  2             1            0            0            0             1\n20  2             1            0            0            0             0\n   feat.keebler feat.nabisco feat.private price.sunshine price.keebler\n1             0            0            0             98            88\n2             0            0            0             99           109\n3             0            0            0             49           109\n4             0            0            0            103           109\n5             0            0            0            109           109\n6             0            0            0             89           109\n7             0            0            0            109           109\n8             0            0            0            109           119\n9             0            0            0            109           121\n10            0            0            0             79           121\n11            0            0            0            109           113\n12            0            0            0            109           121\n13            0            0            0             89           121\n14            0            0            0            109           109\n15            0            0            0            109           109\n16            0            0            0            129           104\n17            0            0            0             79            99\n18            0            0            0             69           105\n19            0            0            0             79           125\n20            0            0            0             79           125\n   price.nabisco price.private   choice\n1            120            71  nabisco\n2             99            71  nabisco\n3            109            78 sunshine\n4             89            78  nabisco\n5            119            64  nabisco\n6            119            84  nabisco\n7            129            78 sunshine\n8            129            78  nabisco\n9            109            78  nabisco\n10           109            78  nabisco\n11           109            96  nabisco\n12            99            86  nabisco\n13            99            86  nabisco\n14           129            96  nabisco\n15           129            79  nabisco\n16           129            96  nabisco\n17            69            69  nabisco\n18            89            65 sunshine\n19           106            69 sunshine\n20           106            69 sunshine\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード8-14\ncracker <- mlogit.data(Cracker, choice = \"choice\", shape = \"wide\",\n                       varying = c(2:13))\nhead(cracker, n = 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n~~~~~~~\n first 20 observations out of 13168 \n~~~~~~~\n   id choice      alt disp feat price chid    idx\n1   1  FALSE  keebler    0    0    88    1 1:bler\n2   1   TRUE  nabisco    0    0   120    1 1:isco\n3   1  FALSE  private    0    0    71    1 1:vate\n4   1  FALSE sunshine    0    0    98    1 1:hine\n5   1  FALSE  keebler    0    0   109    2 2:bler\n6   1   TRUE  nabisco    0    0    99    2 2:isco\n7   1  FALSE  private    0    0    71    2 2:vate\n8   1  FALSE sunshine    0    0    99    2 2:hine\n9   1  FALSE  keebler    0    0   109    3 3:bler\n10  1  FALSE  nabisco    0    0   109    3 3:isco\n11  1  FALSE  private    0    0    78    3 3:vate\n12  1   TRUE sunshine    1    0    49    3 3:hine\n13  1  FALSE  keebler    0    0   109    4 4:bler\n14  1   TRUE  nabisco    0    0    89    4 4:isco\n15  1  FALSE  private    0    0    78    4 4:vate\n16  1  FALSE sunshine    0    0   103    4 4:hine\n17  1  FALSE  keebler    0    0   109    5 5:bler\n18  1   TRUE  nabisco    0    0   119    5 5:isco\n19  1  FALSE  private    0    0    64    5 5:vate\n20  1  FALSE sunshine    0    0   109    5 5:hine\n\n~~~ indexes ~~~~\n   chid      alt\n1     1  keebler\n2     1  nabisco\n3     1  private\n4     1 sunshine\n5     2  keebler\n6     2  nabisco\n7     2  private\n8     2 sunshine\n9     3  keebler\n10    3  nabisco\n11    3  private\n12    3 sunshine\n13    4  keebler\n14    4  nabisco\n15    4  private\n16    4 sunshine\n17    5  keebler\n18    5  nabisco\n19    5  private\n20    5 sunshine\nindexes:  1, 2 \n```\n\n\n:::\n\n```{.r .cell-code}\n# コード8-15\nml_cracker <- mlogit(choice ~ price | 1 | disp + feat, probit = FALSE,\n                     data = cracker)\n\nsummary(ml_cracker)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nmlogit(formula = choice ~ price | 1 | disp + feat, data = cracker, \n    probit = FALSE, method = \"nr\")\n\nFrequencies of alternatives:choice\n keebler  nabisco  private sunshine \n0.068651 0.544350 0.314399 0.072600 \n\nnr method\n5 iterations, 0h:0m:0s \ng'(-H)^-1g = 0.000258 \nsuccessive function values within tolerance limits \n\nCoefficients :\n                       Estimate Std. Error  z-value  Pr(>|z|)    \n(Intercept):nabisco   2.0011226  0.0831336  24.0712 < 2.2e-16 ***\n(Intercept):private   0.3193793  0.1238052   2.5797 0.0098888 ** \n(Intercept):sunshine -0.5435987  0.1139407  -4.7709 1.834e-06 ***\nprice                -0.0300966  0.0021082 -14.2761 < 2.2e-16 ***\ndisp:keebler          0.2999316  0.2070369   1.4487 0.1474251    \ndisp:nabisco          0.1011111  0.0773633   1.3070 0.1912249    \ndisp:private         -0.2244555  0.1495236  -1.5011 0.1333199    \ndisp:sunshine         0.4818670  0.1672400   2.8813 0.0039605 ** \nfeat:keebler          0.6678542  0.2581732   2.5868 0.0096859 ** \nfeat:nabisco          0.6047773  0.1404077   4.3073 1.653e-05 ***\nfeat:private          0.1726981  0.2004446   0.8616 0.3889213    \nfeat:sunshine         0.8304895  0.2340938   3.5477 0.0003886 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nLog-Likelihood: -3333.8\nMcFadden R^2:  0.052798 \nLikelihood ratio test : chisq = 371.66 (p.value = < 2.22e-16)\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# コード8-16\n# パラメータの推定値（beta）の抽出\nbeta <- probit2$coefficients\n\n# パラメータbeta と説明変数の線形結合を作成（beta_0 は定数項なので1 をかける）\nest_probit2 <- cbind(1, choice_df$p_ratio, choice_df$a1,\n                     choice_df$a2) %*% beta\n\n# pnorm によって標準正規分布の分布関数による計算を実行する。\n# 製品1(c1) を選ぶ確率の予測値\npred_probit_c1 <- pnorm(est_probit2)\nmean(pred_probit_c1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4789384\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード8-17\n# ロジットモデルの場合\nlogit2 <- glm(y1 ~ p_ratio + a1 + a2,\n              family = binomial(link = logit),\n              data = choice_df)\nbeta_logit <- logit2$coefficients\nest_logit2 <- cbind(1, choice_df$p_ratio, choice_df$a1,\n                    choice_df$a2) %*% beta_logit\npred_logit_c1 <- (exp(est_logit2)) / (1 + exp(est_logit2))\nmean(pred_logit_c1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.479\n```\n\n\n:::\n\n```{.r .cell-code}\n# コード8-18\nchoice_df_v <- choice_df %>%\n  mutate(p1_v = p1 - 1,\n         p_ratio_v = p1_v - p2)\nest_probit_v <- cbind(1, choice_df_v$p_ratio_v, choice_df_v$a1,\n                      choice_df_v$a2) %*% beta\n\n# pnorm によって標準正規分布の分布関数による計算を実行する。\n# 製品1(c1) を選ぶ確率の予測値\npred_probit_v <- pnorm(est_probit_v)\nmean(pred_probit_v)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.5459071\n```\n\n\n:::\n:::\n\n\n",
    "supporting": [
      "chapter08_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}